server:
  port: 8181
spring:
  security:
    oauth2:
      client:
        provider:
          my-client:
            token-uri: "https://dev-f4xax50bmjqj2knx.us.auth0.com/oauth/token"
        registration:
          my-client:
            client-id: "Cao5x6x1XttRii2HwGqAye3eb0UdsUdr"
            client-secret: "b71QJKijBQwju1Bc6OSKh7DIFfx-7HOnPKgtqL4vLtA6P33GP8wlGyHECcc21v4U"
            authorization-grant-type: "client_credentials"

app:
  oauth2:
    audience: "http://games-api"